const menu = [
    {
        id: 0,
        image: "/menu4.webp",
        menu_name: "Jumble Stir Fried Seafood",
        description: "Now with corn and potato marbles! Our bestselling stir fried mix of lobster, crab, shrimp, mussels, clams, scallops & crab roe balls in our signature flavor of your choice.",
        price: parseFloat("1999"),
        quantity: 1,
    },
    {
        id: 1,
        image: "/menu5.webp",
        menu_name: "Lobsters",
        description: "Stir Fried Lobsters With Your Choice Of Flavor (500 Grams Per Order)",
        price: parseFloat("1599"),
        quantity: 1,
    },
    {
        id: 2,
        image: "/menu6.webp",
        menu_name: "Crabs",
        description: "Stir Fried Lobsters With Your Choice Of Flavor (500 Grams Per Order)",
        price: parseFloat("1399"),
        quantity: 1,
    },
    {
        id: 3,
        image: "/menu7.webp",
        menu_name: "Shrimps",
        description: "Stir Fried Shrimp With Your Choice Of Flavor (500 Grams Per Order)",
        price: parseFloat("699"),
        quantity: 1,
    },
    {
        id: 4,
        image: "/menu8.webp",
        menu_name: "Seashell Mix",
        description: "Stir Fried Seashell Mix With Your Choice Of Flavor (500 Grams Per Order)",
        price: parseFloat("599"),
        quantity: 1,
    },
    {
        id: 5,
        image: "/menu9.webp",
        menu_name: "8 pcs. Mixed Wings",
        description: "Fried Chicken Wings Coated In Our Signature Flavors Of Your Choice",
        price: parseFloat("279"),
        quantity: 1,
    },
    {
        id: 6,
        image: "/menu10.webp",
        menu_name: "8-pcs. Go Naked Wings",
        description: "Fried Chicken Wings With Your Choice Of Flavors On The Side",
        price: parseFloat("279"),
        quantity: 1,
    },
    {
        id: 7,
        image: "/menu11.webp",
        menu_name: "Two-Piece Louisiana Fried Chicken",
        description: "Two-Piece Louisiana Fried Chicken (With Rice & Drink)",
        price: parseFloat("189"),
        quantity: 1,
    },
    {
        id: 8,
        image: "/menu12.webp",
        menu_name: "6-Pcs. Louisiana Fried Chicken",
        description: "",
        price: parseFloat("559"),
        quantity: 1,
    },
    {
        id: 9,
        image: "/menu13.webp",
        menu_name: "Fish Surprise & Fries",
        description: "Deep Fried Tilapia Fillet & Fries With Tartar Dip",
        price: parseFloat("279"),
        quantity: 1,
    }
    
];

module.exports = { menu };